package com.ecfeed.spec.gui;

public enum EChildrenImplementationStatus {
	NO_CHILDREN,
	ALL_NOT_IMPLEMENTED,
	SOME_PARTLY_IMPLEMENTED_REST_NOT_IMPLEMENTED,
	ALL_PARTLY_IMPLEMENTED,
	SOME_IMPLEMENTED_REST_NOT_IMPLEMENTED,
	SOME_IMPLEMENTED_REST_PARTLY_IMPLEMENTED,
	ALL_IMPLEMENTED,
	FULL_MIX
}
