package com.testify.ecfeed.abstraction.operations;

public interface OperationNames {
	public static String RENAME = "Rename";
	public static String SET_DEFAULT_VALUE = "Set default value";
	public static String SET_EXPECTED_STATUS = "Change expected status";
	public static String SET_TYPE = "Set type";
	public static String ADD_METHOD = "Add method";
	public static String ADD_METHODS = "Add methods";
	public static String REMOVE_METHOD = "Remove method";
	public static String EDIT_STATEMENT = "Edit statement";
	public static String CHANGE_STATEMENT_OPERATOR = EDIT_STATEMENT;
	public static String REPLACE_STATEMENT = EDIT_STATEMENT;
	public static String REMOVE_STATEMENT = "Remove statement";
	public static String SET_STATEMENT_CONDITION = EDIT_STATEMENT;
	public static String SET_STATEMENT_RELATION = EDIT_STATEMENT;
	public static String ADD_CHILDREN = "Add elements";
	public static String MOVE = "Move elements";
	public static String REMOVE_PARTITION = "Remove partition";
	public static String ADD_PARTITION = "Add partition";
	public static String REMOVE_NODES = "Remove elements";
	public static String ADD_CONSTRAINT = "Add constraint";
	public static String ADD_PARAMETER = "Add parameter";
	public static String ADD_TEST_CASE = "Add test case";
	public static String ADD_TEST_CASES = "Add test cases";
	public static String CONVERT_METHOD = "Convert method";
	public static String MAKE_CONSISTENT = "Make method consistent";
	public static String REMOVE_CONSTRAINT = "Remove constraint";
	public static String REMOVE_PARAMETER = "Remove parameter";
	public static String REMOVE_TEST_CASE = "Remove test case";
	public static String RENAME_TEST_CASE = "Rename test case";
	public static String ADD_PARTITION_LABEL = "Add partition label";
	public static String ADD_PARTITION_LABELS = "Add partition labels";
	public static String REMOVE_PARTITION_LABEL = "Remove partition label";
	public static String REMOVE_PARTITION_LABELS = "Remove partition labels";
	public static String RENAME_LABEL = "Rename label";
	public static String SET_PARTITION_VALUE = "Set partition value";
	public static String ADD_CLASSES = "Add classes";
	public static String ADD_CLASS = "Add class";
	public static String REMOVE_CLASS = "Remove class";
	public static String ADD_STATEMENT = "Add statement";
	public static String UPDATE_TEST_DATA = "Update test data";
}
