package com.testify.ecfeed.spec.gui;

public enum ESelectionType{
	SINGLE_FIRST_INDEX, SINGLE_MIDDLE_INDEX, SINGLE_LAST_INDEX,
	SINGLE_TYPE_MULTIPLE_NODES, SINGLE_TYPE_MULTIPLE_PARENTS,
	MULTIPLE_TYPES_CLUSTERED, MULTIPLE_TYPES_INTERLEAVED, MULTIPLE_TYPE_MULTIPLE_PARENTS;
}
